services:
  server:
    build:
      context: .
      target: dev
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "--destination", "github-pages-out"]
    volumes:
      - ./github-pages-out:/src/github-pages-out
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/