services:
  server:
    build:
      context: .
      target: build-base
    ports:
      - "1313:1313"
    # If upstream changes "/project/public", use
    # entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
    # for the next line and jump into the container to see the latest doc path
    entrypoint: ["hugo", "--destination", "/project/public"]
    volumes:
      - ${DEPLOYMENT_DIR}:/project/public
    develop:
      watch:
        - action: sync
          path: .
          target: /project
