# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Deploy Docs to GitHub Pages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reuse upstream's build logic and, when done, fetch them out from container into "github-pages-out" on host
        run: mkdir github-pages-out && docker compose up
      - name: Load CNAME
        run: echo docker.qubitpi.org > github-pages-out/CNAME
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: github-pages-out
          enable_jekyll: true
          user_name: QubitPi
          user_email: jack20220723@gmail.com
